spring.application.name=scm
server.port=8081


#Mysql database Configuration
#database source url
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=root

#jpa configuration
spring.jpa.hibernate.ddl-auto=update

#spring.security.user.name=arup
#spring.security.user.password=arup

# To config oauth id secret

spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=google id 
spring.security.oauth2.client.registration.google.client-secret=Google secret
spring.security.oauth2.client.registration.google.scope=profile, email



spring.security.oauth2.client.registration.github.client-id=Iv23li6QN14GfZKtHJfL
spring.security.oauth2.client.registration.github.client-secret=208c5459b1182b9a7075361bbf49ba70eca80313
spring.security.oauth2.client.registration.github.scope=profile,email


cloudinary.cloud.name=dyhwk1ghz
cloudinary.api.key=445847999559526
cloudinary.api.secret=SndRR3i73UZv9xQ2NY54YpUXOqI